# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pedroluyo/web-gastroconnect:latest
        ports:
        - containerPort: 4200

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 4200 

---
# Backend - Dishes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-dishes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-dishes
  template:
    metadata:
      labels:
        app: ms-dishes
    spec:
      containers:
      - name: ms-dishes
        image: pedroluyo/ms-dishes:latest
        ports:
        - containerPort: 8081

---
# Backend - Dishes Service
apiVersion: v1
kind: Service
metadata:
  name: ms-dishes-service
spec:
  type: LoadBalancer
  selector:
    app: ms-dishes
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081

---
# Backend - Restaurants Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-restaurants-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-restaurants
  template:
    metadata:
      labels:
        app: ms-restaurants
    spec:
      containers:
      - name: ms-restaurants
        image: pedroluyo/ms-restaurants:latest
        ports:
        - containerPort: 8082

---
# Backend - Restaurants Service
apiVersion: v1
kind: Service
metadata:
  name: ms-restaurants-service
spec:
  type: LoadBalancer
  selector:
    app: ms-restaurants
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082

---
# Backend - Bookings Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-bookings-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-bookings
  template:
    metadata:
      labels:
        app: ms-bookings
    spec:
      containers:
      - name: ms-bookings
        image: pedroluyo/ms-bookings:latest
        ports:
        - containerPort: 8083

---
# Backend - Bookings Service
apiVersion: v1
kind: Service
metadata:
  name: ms-bookings-service
spec:
  type: LoadBalancer
  selector:
    app: ms-bookings
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083

---
# Backend - Notifications Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notifications-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-notifications
  template:
    metadata:
      labels:
        app: ms-notifications
    spec:
      containers:
      - name: ms-notifications
        image: pedroluyo/ms-notifications:latest
        ports:
        - containerPort: 8084

---
# Backend - Notifications Service
apiVersion: v1
kind: Service
metadata:
  name: ms-notifications-service
spec:
  type: LoadBalancer
  selector:
    app: ms-notifications
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
