apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: angelolm/unificado:latest
        ports:
        - containerPort: 4200
        env:
        - name: letterplate
          value: "http://ms-letterplate-service"  
        - name: restaurantmenu
          value: "http://ms-restaurantmenu-service"  
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 4200 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-restaurantmenu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-restaurantmenu
  template:
    metadata:
      labels:
        app: ms-restaurantmenu
    spec:
      containers:
      - name: ms-restaurantmenu
        image: pedroluyo/ms-restaurantmenu:latest
        ports:
        - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: ms-restaurantmenu-service
spec:
  type: LoadBalancer
  selector:
    app: ms-restaurantmenu
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-letterplate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-letterplate
  template:
    metadata:
      labels:
        app: ms-letterplate
    spec:
      containers:
      - name: ms-letterplate
        image: alexito03/ms-letterplate:latest
        ports:
        - containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: ms-letterplate-service
spec:
  type: LoadBalancer
  selector:
    app: ms-letterplate
  ports:
  - protocol: TCP
    port: 9095  
    targetPort: 9095  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-restaurant
  template:
    metadata:
      labels:
        app: ms-restaurant
    spec:
      containers:
      - name: ms-restaurant
        image: erickportuguez/ms-restaurant:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: ms-restaurant-service
spec:
  type: LoadBalancer
  selector:
    app: ms-restaurant
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-menuplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-menuplate
  template:
    metadata:
      labels:
        app: ms-menuplate
    spec:
      containers:
      - name: ms-menuplate
        image: naomicama/ms-menuplate:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ms-menuplate-service
spec:
  type: LoadBalancer
  selector:
    app: ms-menuplate
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    
