server:
  port: 8083



spring:

  application:
    name: bookings-service

  r2dbc:
    url: r2dbc:postgresql://db-bookings-gc-phpl-12d9.k.aivencloud.com:26287/db-bookings?sslmode=require
    username: avnadmin
    password: AVNS_9iyWAkTF185N9KM7fJY

  datasource:
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: pkc-4v5zz.sa-east-1.aws.confluent.cloud:9092
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='JOF7TEJBGQ2VCW2Z' password='m8SMtW/6y74KnEQTa9BeZH6GD9ptnPfWS0cvCAfE3efIr8p0PXKCgaVskb3Cqfmv';
        mechanism: PLAIN
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer